# Generated by Django 5.0.7 on 2024-07-22 14:28

import core.models
import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.gen_file_path, variations={'thumb': {'crop': True, 'height': 450, 'width': 450}}, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.position', verbose_name='Position'),
        ),
    ]
